### ISSUE TITLE
[Feature]: String Manager

### ISSUE THREAD

**Issue by raredeveloperofc** [itsvks19/LayoutEditor#26]
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

Can I try putting the String Manager? 

### Additional context

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsvks19** [comment]
Yeah. Sure.

**Comment by raredeveloperofc** [comment]
Ok

**Comment by itsvks19** [comment]
Okay. You can directly contact me on telegram.

**Comment by raredeveloperofc** [comment]
I don't have telegram, only instagram

**Comment by itsvks19** [comment]
Oh nice. So you can directly contact me on Instagram

**Comment by raredeveloperofc** [comment]
what is your Instagram?

**Comment by itsvks19** [comment]
@vivek_k__sahani

**Comment by TimScriptov** [comment]
@itsvks19 I would like to join the development team ApkEditor Pro(Android Studio, kotlin, java)

My telegram:
@timscriptov

My channel:
https://t.me/apkeditorproofficial

**Comment by itsvks19** [comment]
Okay. You can join.

**Comment by TimScriptov** [comment]
> @TimScriptov Okay. You can join.

Sorry mistake. I invite you to my development team. We develop ApkEditor Pro and ApkProtector

**Comment by itsvks19** [comment]
But why?

**Comment by TimScriptov** [comment]
![Screenshot_20230302-090426_APK_Editor_Pro.png](https://user-images.githubusercontent.com/31324315/222328393-4585ff9e-477c-4a81-8973-2b5221004563.png)

![Screenshot_20230302-090439_APK_Editor_Pro.png](https://user-images.githubusercontent.com/31324315/222328401-44ecae85-564c-4158-a311-010e66c7f01e.png)

![Screenshot_20230302-090445_APK_Editor_Pro.png](https://user-images.githubusercontent.com/31324315/222328404-6970ff93-0466-4cee-8f9c-dff0b69926d8.png)

![Screenshot_20230302-090450_APK_Editor_Pro.png](https://user-images.githubusercontent.com/31324315/222328406-89b1ae0b-91e1-4cd8-b442-e45c5dfde5b0.png)

**Comment by itsvks19** [comment]
Nice

**Comment by TimScriptov** [comment]
> But why?

You good dev. That's why I want to invite you to my team

**Comment by TimScriptov** [comment]
> But why?

You good dev. That's why I want to invite you to my team

**Comment by itsvks19** [comment]
Is it private repo?

**Comment by TimScriptov** [comment]
> Is it private repo?

Right

**Comment by itsvks19** [comment]
Okay
