### ISSUE TITLE
[Feature]: Vector mode View

### ISSUE THREAD

**Issue by moderGamer** [itsvks19/LayoutEditor#34]
### Is your feature request related to a problem? Please describe.

Hello, if possible, add the feature of displaying vector photos

### Describe the solution you'd like

*

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andihasan97** [comment]
Including google assets with the .xml extension, right?

**Comment by moderGamer** [comment]
tnks bro

**Comment by itsvks19** [comment]
@moderGamer Thanks

**Comment by moderGamer** [comment]
![Screenshot_20230309-200219_GhostWeb IDE](https://user-images.githubusercontent.com/125615066/224089659-1e25f165-9081-4e9d-9dab-18470ee03600.jpg)

for me good work try it to add Your Project See VectorMaster
@itsvks19

**Comment by itsvks19** [comment]
Okay

**Comment by itsvks19** [comment]
Completed in #348bdf8

**Comment by itsvks19** [comment]
Completed in #348bdf8

**Comment by itsvks19** [comment]
Completed in [348bdf8](https://github.com/itsvks19/LayoutEditor/commit/348bdf8667c8aa0a2599a6d9a3d05bbb2820980d)
