### ISSUE TITLE
Consider using Sheets instead of Navigation drawer in editor

### ISSUE THREAD

**Issue by RivanParmar** [itsvks19/LayoutEditor#39]
### Is your feature request related to a problem? Please describe.

It's a bit frustrating when trying to select a component from the Navigation drawer. The drawer closes while switching between the tabs. Moreover, tabs in the navigation drawer aren't recommended as per the Material 3 guidelines.

### Describe the solution you'd like

Consider using a Bottom sheet for compact devices and a Side sheet for tablets and desktops. I would suggest to not use modal sheets as they create a scrim over the main content. Also, another option would be to remove the tabs from the Navigation drawer and instead use a drop-down structure.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsvks19** [comment]
@RivanParmar Where should I put these components?

**Comment by itsvks19** [comment]
@RivanParmar How do I know if the device is small or large?

**Comment by RivanParmar** [comment]
You could try using WindowSizeClass or you could create alternate layout resources like `res/layout-w600dp` for tablets. For more information you can check this link: [](https://developer.android.com/guide/topics/large-screens/support-different-screen-sizes)

**Comment by itsvks19** [comment]
Replaced `TabLayout` with `NavigationRail`.
