### ISSUE TITLE
Feature Request: Add a layout manager 

### ISSUE THREAD

**Issue by Reza478** [itsvks19/LayoutEditor#40]
Plz add a file manager for the project that we can  easily add and remove layouts and items

**Comment by raredeveloper** [comment]
I don't think a file explorer would be good. Maybe the solution is to add a layout manager to the project like Sketchware

**Comment by itsvks19** [comment]
@raredeveloper Yeah. It would be nice to add a layout manager like Sketchware.

**Comment by itsvks19** [comment]
Done
