### ISSUE TITLE
Image drawable problem

### ISSUE THREAD

**Issue by learnerscafe** [itsvks19/LayoutEditor#42]
Please look into this problem of mine. The app has all permissions taken. But when I want to take the image drawable a popup comes Permission denide. But when I take vector drawable nothing issues it's working. Only problem image drawable.

**Comment by itsvks19** [comment]
@learnerscafe Can you tell me what is the android version of your phone?

**Comment by iyoedHUB** [comment]
Please, i cannot open image drawable, vector is work to open. Thanks
