### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by sb-codz** [itsvks19/LayoutEditor#53]
Please add <androidx.coordinatorlayout>
And other androidx support library.

**Comment by itsvks19** [comment]
Hmm. I'll add it.

**Comment by sb-codz** [comment]
Bro I am unable to download the last debug version from the action section. Do I want to load the last debug version?

**Comment by itsvks19** [comment]
Download [this](https://github.com/itsvks19/LayoutEditor/actions/runs/7583301783).
