### ISSUE TITLE
buttons within a linear_layout (H) are not laid out correctly

### ISSUE THREAD

**Issue by appdevforall** [itsvks19/LayoutEditor#58]
The following code snippet was created using the layout editor

`<android.widget.LinearLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:orientation="vertical">

	<android.widget.TextView
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:text="@string/default_string"
		android:gravity="center_horizontal"
		android:layout_marginLeft="50"
		android:layout_marginTop="100" />

	<android.widget.EditText
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:hint="Password"
		android:inputType="textPassword" />

	<android.widget.Button
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:text="Button" />

	<android.widget.LinearLayout
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:orientation="horizontal"
		android:padding="8dp"
		android:layout_gravity="center_horizontal|fill_horizontal"
		android:weightSum="2"
		android:gravity="center_horizontal"
		android:layout_marginLeft="10dp"
		android:layout_marginRight="10dp">

		<android.widget.Button
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:text="Button"
			android:layout_weight="1"/>

		<android.widget.Button
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:text="Button"
			android:layout_weight="1"/>

	</android.widget.LinearLayout>
`

in both the editor and the preview, the buttons are grouped together in the center of the linear_layout, however if the XML is exported and added to the Android Studio layout editor, the buttons will fill the parent equally as defined by the layout weights

**Comment by itsvks19** [comment]
@appdevforall Is it generating full name of widgets like "android.widget.LinearLayout" not only LinearLayout ??

**Comment by appdevforall** [comment]
If I understand your question correctly the included code shows

<android.widget.LinearLayout

is that what you were asking or did you mean in the code?

**Comment by itsvks19** [comment]
> in both the editor and the preview, the buttons are grouped together in the center of the linear_layout, however if the XML is exported and added to the Android Studio layout editor, the buttons will fill the parent equally as defined by the layout weights

Can you explain me what is the problem? Send a screen recording if possible.

**Comment by itsvks19** [comment]
Oh understand now 😅

**Comment by yaturner** [comment]
thank you, it works now
