### ISSUE TITLE
Cannot open image drawable

### ISSUE THREAD

**Issue by iyoedHUB** [itsvks19/LayoutEditor#62]
Please i cannot open image drawable. vector open is work normally. Thanks

**Comment by itsvks19** [comment]
provide a screen recording if possible

**Comment by iyoedHUB** [comment]
Please fix this thanks for your attention

Pada Sen, 29 Apr 2024 13.07, Vivek Kumar Sahani ***@***.***>
menulis:

**Comment by itsvks19** [comment]
@iyoedHUB ??

**Comment by iyoedHUB** [comment]
> provide a screen recording if possible

[Uploading image drawable cannot open.zip…]()
